import cors from "cors";
import path from "path";
import express from "express";
import fileupload from "express-fileupload";
import userRouter from "./routers/user.routes.js";
import articleRouter from "./routers/article.routes.js";
const app = express();
const PORT = process.env.PORT || 5050;
app.use(cors({ origin: "*" }));
app.use(express.json());
app.use(express.static(path.join(process.cwd(), "avatarka")));
app.use(fileupload({ limits: { fileSize: 10 * 1024 * 1024 } }));
app.use(userRouter);
app.use(articleRouter);
app.listen(PORT);
console.log("Connection:!", "http://localhost:" + PORT);
